### ISSUE TITLE
Read boot.elf failed

### ISSUE THREAD

**Issue by K16DIABLO** [cnrv/fpga-rocket-chip#10]
Hi, I'm implementing the fpga shell for ASIC on VC707 using this repo. My shell stops when it calls _f_read(&fil, buf, SD_READ_SIZE, &br)_, but I cannot find what the problem is. The configuration is almost same as this repo. Can you help me?

**Comment by wsong83** [comment]
As I do not have this board on hand and have no experience in using fpga shell, I cannot help directly.
For my own experience, you would be better to have the underlying SPI (if you use the SPI mode for SD) worked properly beforing trying reading a file from SD.

**Comment by wsong83** [comment]
Since we do not have resource to support any porting effort other than Nexys4-DDR, this issue is closed.
