### ISSUE TITLE
Porting to other FPGA boards

### ISSUE THREAD

**Issue by shivampotdar** [cnrv/fpga-rocket-chip#11]
Thank you for creating the project. I appreciate the fact that it has a much newer version compared to the lowRISC SoC.

I was wondering what would be the steps one would have to take to remap this flow onto a different FPGA board. 
I am working on a Xilinx ZCU102. At least to start with, I think I would just load the bitstream directly over JTAG to avoid the complexities with PS, or if needed I think some references can be taken from the (fpga-zynq)[https://github.com/li3tuo4/rc-fpga-zcu]
I understand that most of the changes would be in the parameters in https://github.com/li3tuo4/rc-fpga-zcu this section. Aside from that can you please guide me on what other factors would I have to consider?

Thank you

**Comment by wsong83** [comment]
As we do not have any ZCU board aorund, I have no idea how difficult it would be. For a pure FPGA board, such as Nexys4-DDR, KC705 or VC707, downloading a bitstream is not a big issue. The same bitstream can be downloaded using SD, Jtag or Flash.

However, for a board mounted with a Zynq FPGA, I think the major issue is whether you need to get rid of the ARM core or utilize the ARM core. Your choice leads to the various changes required for the porting and these are the main tasks.

I am afraid I cannot be very helpful here.
