### ISSUE TITLE
Error in running make file of bootrom.

### ISSUE THREAD

**Issue by Talha-Ahmed-1** [cnrv/fpga-rocket-chip#13]
I tried running the ```make vivado_source``` but it gives me this error regarding the make file bootrom.
I executed the make command in bootrom of rocket-chip separately it runs perfectly fine.
Does anyone know how to resolve this error?

![vivado](https://user-images.githubusercontent.com/52505840/99494087-34a31880-2992-11eb-9d4d-846c5ab67087.png)

**Comment by wsong83** [comment]
I failed to reproduce this error on my machine.
This type of errors (asking for cc1 compiler but should not) might caused by your environment settings.
I would suggest you retry from scratch and on a clean shell (no PATH modification in the bashrc script or anything related).
