### ISSUE TITLE
How to debug the program using gdb in this project

### ISSUE THREAD

**Issue by stwjt** [cnrv/fpga-rocket-chip#18]
I have finished debugging the program in rocketchip's emulator by adding the WithJtagDTM. However, I do not know how to debug the program using gdb in rocketchip. Would you like to give me a hint?

**Comment by wsong83** [comment]
Oops, I am afraid utilizing the run-control debug through gdb is one of the many features we do not know how to operate yet. Just in case, if you figure it out in the future, we would be very happy to have it for this repo.

**Comment by stwjt** [comment]
> Oops, I am afraid utilizing the run-control debug through gdb is one of the many features we do not know how to operate yet. Just in case, if you figure it out in the future, we would be very happy to have it for this repo.

Thank you for your reply! I'd like to know the ways you use to debug(bootloader or kernel). In Firesim, It has [tracerv](https://github.com/firesim/firesim/blob/7e32128bea/sim/firesim-lib/src/main/cc/bridges/tracerv.cc). I would like to know if we can utilize tracerv in this project. Some programs have no problem running on QEMU, but they have several problems running on FPGA.

**Comment by wsong83** [comment]
No magic here. Bring up the terminal as soon as possible so you can print something. The BBL used as the bootloader can print stuff directly to UART while the kernel's printk print stuff to UART as well through the sbi interface.

To the best of my knowledge, firesim is a simulator while fpga-rocket-chip is a real processor running on a FPGA. You can think the latter as a black-box unless some sort of trace debugger is implemented inside.

**Comment by stwjt** [comment]
> No magic here. Bring up the terminal as soon as possible so you can print something. The BBL used as the bootloader can print stuff directly to UART while the kernel's printk print stuff to UART as well through the sbi interface.
> 
> To the best of my knowledge, firesim is a simulator while fpga-rocket-chip is a real processor running on a FPGA. You can think the latter as a black-box unless some sort of trace debugger is implemented inside.

Thank you for your advice. I think I know what to do next.
