### ISSUE TITLE
2.1.3 Adding Peri IPs

### ISSUE THREAD

**Issue by nicolast0604** [cnrv/fpga-rocket-chip#4]
Could you please tell me steps by steps how to do it in Vivado as I am not familiar with Vivado yet?

**Comment by NeutrinoLiu** [comment]
briefly speaking, click IP CATALOG -> Search and Choose IP -> Customize the IP. A tutorial is here, [UG939](https://www.xilinx.com/support/documentation/sw_manuals/xilinx2019_1/ug939-vivado-designing-with-ip-tutorial.pdf)
