### ISSUE TITLE
Shouldn't M02_AXI > 7?

### ISSUE THREAD

**Issue by nicolast0604** [cnrv/fpga-rocket-chip#5]
Shouldn't M02_AXI > 7,
your tutorial said 7 flags error.

**Comment by NeutrinoLiu** [comment]
that's true, the version of my Vivado is 2016.4, in which width of 7 works. In the latest version there is a constraint of width, expected to be greater than 12. **you need to set M02_AXI to 12 here** (as a consequence partial of the address space is wasted). I will change this document and the dts file later.
