### ISSUE TITLE
Error: Implementation failed with error [Opt 31-430] Found a FDRE that its data pin is undriven.

### ISSUE THREAD

**Issue by SivaMounikaPeddineni** [cnrv/fpga-rocket-chip#6]
When tried to generate the bit stream below error is encountered at the implementation stage.
Error:
[Opt 31-430] Found a FDRE that its data pin is undriven. Driver is required to prevent unexpected behavior:mmio/peri_Xbar/inst/gen_samd.crossbar_samd/addr_arbiter_ar/gen_no_arbiter.m_mesg_i_reg[46].

Please find the attached image for critical warning details. Kindly, help us  to resolve this issue.

![Screenshot from 2019-10-23 23-30-25](https://user-images.githubusercontent.com/47664586/67421544-5777c780-f5ee-11e9-8dc6-7d5c2e1b2a0e.png)

**Comment by wsong83** [comment]
The synthesis has already failed which means there is no point to go further to implementation.
From the error message of synthesis, it looks like you did not correctly generate the clock converter (a Xilinx IP block) for the design, otherwise it should not be recognized as a blackblox.

**Comment by SivaMounikaPeddineni** [comment]
Thanks for your response. We will work on it

**Comment by wsong83** [comment]
Close. Reopen if needed.
