### ISSUE TITLE
Boot linux fail.

### ISSUE THREAD

**Issue by Wcm926** [cnrv/fpga-rocket-chip#8]
When we boot linux, the BBL shows the message "Console works fine.", then the whole progress stucks.  How to deal with it?

**Comment by wsong83** [comment]
We probably need more information to guess what happened. For example, did you generate your Linux image using all the exact versions of BBL, busybox, and Linux kernel?

**Comment by K16DIABLO** [comment]
I encountered same issue, and I resolved it. You'd better use linux kernel version mentioned in README. Newer version requires new options, and it seems they cause this problem.

**Comment by wsong83** [comment]
Potentially the issue is resolved, so close it for now.
